### ISSUE TITLE
Always saying Authentication failed

### ISSUE THREAD

**Issue by ghost** [appsroxcom/OwnChat#1]
While I am trying to enter the app it's always shows a loading page then after 2-3 second it's return a tost Authentication failed and close the activity. I have build the real OwnChat and this happening. Can you please explain why?

**Comment by ghost** [comment]
Bessi

> While I am trying to enter the app it's always shows a loading page then after 2-3 second it's return a tost Authentication failed and close the activity. I have build the real OwnChat and this happening. Can you please explain why?
It's happening on UsersActivity.java

**Comment by appsroxcom** [comment]
Try to run a simple Firebase app with authentication first. There are a few steps involved which are described in the Firebase official documentation. Please make sure the google services json and applicationId (package name) matches with your Firebase project.

**Comment by ghost** [comment]
Every firebase authentication working fine.
